var CHECKED="29 Sep 2026";
function M(s){return '<span class="path">'+s+'</span>';}
var LAWS=[
{id:"th",where:{en:"Thailand",th:"ไทย"},law:"PDPA B.E. 2562",rights:{en:"copy s.30 · take it elsewhere s.31 · delete s.33",th:"ขอสำเนา ม.30 · ขอไฟล์ไปใช้ที่อื่น ม.31 · ขอลบ ม.33"},time:{en:"30 days",th:"30 วัน"},cite:"sections 30 and 31 of Thailand's Personal Data Protection Act B.E. 2562 (2019)",due:"within 30 days of receiving this request",src:"https://cc.kmutt.ac.th/Files/Act%20Eng/personal-data-protection-act-2019-en.pdf"},
{id:"eu",where:{en:"European Union",th:"สหภาพยุโรป"},law:"GDPR",rights:{en:"copy Art.15 · take it elsewhere Art.20 · delete Art.17",th:"ขอสำเนา ม.15 · ขอไฟล์ไปใช้ที่อื่น ม.20 · ขอลบ ม.17"},time:{en:"1 month (up to 3)",th:"1 เดือน (ขยายได้ถึง 3)"},cite:"Articles 15 and 20 of the General Data Protection Regulation (GDPR)",due:"within one month of receiving this request, as Article 12(3) requires",src:"https://eur-lex.europa.eu/eli/reg/2016/679/oj"},
{id:"uk",where:{en:"United Kingdom",th:"สหราชอาณาจักร"},law:"UK GDPR",rights:{en:"copy Art.15 · take it elsewhere Art.20 · delete Art.17",th:"ขอสำเนา ม.15 · ขอไฟล์ไปใช้ที่อื่น ม.20 · ขอลบ ม.17"},time:{en:"1 month",th:"1 เดือน"},cite:"Articles 15 and 20 of the UK GDPR",due:"within one month of receiving this request",src:"https://www.gov.uk/guidance/data-use-and-access-act-2025-data-protection-and-privacy-changes"},
{id:"ca",where:{en:"California",th:"แคลิฟอร์เนีย"},law:"CCPA / CPRA",rights:{en:"copy §1798.110 · usable format §1798.130 · delete §1798.105",th:"ขอสำเนา §1798.110 · ไฟล์ที่เอาไปใช้ได้ §1798.130 · ขอลบ §1798.105"},time:{en:"45 days (up to 90)",th:"45 วัน (ขยายได้ถึง 90)"},cite:"the California Consumer Privacy Act (Cal. Civ. Code §§1798.100, 1798.110 and 1798.130)",due:"within 45 days of receiving this request",src:"https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=CIV&sectionNum=1798.130"},
{id:"br",where:{en:"Brazil",th:"บราซิล"},law:"LGPD",rights:{en:"copy, take it elsewhere, delete: Art.18",th:"ขอสำเนา ขอไฟล์ไปใช้ที่อื่น ขอลบ: ม.18"},time:{en:"15 days",th:"15 วัน"},cite:"Articles 18 and 19 of Brazil's General Data Protection Law (LGPD)",due:"within 15 days of receiving this request, as Article 19 requires",src:"https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709compilado.htm"},
{id:"other",where:{en:"Somewhere else",th:"ที่อื่น"},law:{en:"your local data law",th:"กฎหมายข้อมูลส่วนบุคคลที่คุณอยู่"},rights:{en:"most cover a copy and deletion",th:"ส่วนใหญ่ให้ขอสำเนาและขอลบได้"},time:{en:"varies",th:"แล้วแต่ที่"},cite:"the data protection law that applies where I live, and your own privacy policy",due:"within the time that law and your privacy policy allow"}
];
var PLATFORMS=[
{id:"chatgpt",name:"ChatGPT",company:"OpenAI",
 export:{en:"Settings → Data controls → Export data → Export, then confirm.",th:"ไปที่ Settings → Data controls → Export data → Export แล้วกดยืนยัน"},exportSrc:"https://help.openai.com/en/articles/7260999",
 arrives:{en:"A ZIP file by email, within 7 days. The link works for 24 hours. Not on Business or Enterprise plans.",th:"ไฟล์ ZIP ส่งมาทางอีเมล ภายใน 7 วัน ลิงก์ใช้ได้ 24 ชั่วโมง แพ็กเกจ Business และ Enterprise ทำไม่ได้"},
 memory:{en:"Memories: "+M("Settings → Personalization → Memory")+". Instructions: "+M("Settings → Personalization → Custom instructions")+" (phone: Customize ChatGPT).",th:"ความจำ: "+M("Settings → Personalization → Memory")+" คำสั่ง: "+M("Settings → Personalization → Custom instructions")+" (ในมือถือ: Customize ChatGPT)"},memorySrc:"https://help.openai.com/en/articles/8590148",
 import:{en:"No import button. Paste the moving letter into a new chat and ask it to remember.",th:"ไม่มีปุ่มนำเข้า วางจดหมายย้ายบ้านในแชทใหม่ แล้วบอกให้จำไว้"},
 instr:{en:"Put how you like answers into "+M("Settings → Personalization → Custom instructions")+".",th:"ใส่วิธีที่คุณชอบให้ตอบลงใน "+M("Settings → Personalization → Custom instructions")},instrSrc:"https://help.openai.com/en/articles/8096356",
 training:{en:"Settings → Data controls → turn off “Improve the model for everyone”.",th:"Settings → Data controls → ปิด “Improve the model for everyone”"},trainingSrc:"https://help.openai.com/en/articles/7730893",
 remove:{en:"Settings → Account → Delete. OpenAI deletes the data within 30 days.",th:"Settings → Account → Delete ข้อมูลถูกลบภายใน 30 วัน"},removeSrc:"https://help.openai.com/en/articles/6378407",
 privacy:{to:"privacy.openai.com",url:"https://privacy.openai.com/"}},
{id:"claude",name:"Claude",company:"Anthropic",
 export:{en:"Settings → Privacy → Export data. On the website or desktop app; the phone app can't.",th:"Settings → Privacy → Export data ทำในเว็บหรือแอปคอมพิวเตอร์ ในมือถือทำไม่ได้"},exportSrc:"https://support.claude.com/en/articles/9450526",
 arrives:{en:"A link by email. Sign in to download. It works for 24 hours.",th:"ลิงก์ส่งมาทางอีเมล ต้องล็อกอินก่อนดาวน์โหลด ใช้ได้ 24 ชั่วโมง"},
 memory:{en:"Memories: "+M("Settings → Memory")+". Instructions: "+M("Settings → Instructions for Claude")+". Each Project has its own instructions too.",th:"ความจำ: "+M("Settings → Memory")+" คำสั่ง: "+M("Settings → Instructions for Claude")+" แต่ละ Project มีคำสั่งของตัวเองด้วย"},memorySrc:"https://support.claude.com/en/articles/12123587",
 import:{en:M("Settings → Memory → Start import")+". Claude gives you a prompt to run at the old AI; paste its answer back. Brings memory, not chat history. Free and paid plans, website and desktop.",th:M("Settings → Memory → Start import")+" Claude ให้ข้อความไปถาม AI ตัวเก่า แล้วเอาคำตอบมาวาง ได้ความจำ ไม่ได้แชทเก่า ใช้ได้ทั้งฟรีและจ่ายเงิน ในเว็บและแอปคอมพิวเตอร์"},importSrc:"https://support.claude.com/en/articles/12123587",
 instr:{en:"Put how you like answers into "+M("Settings → Instructions for Claude")+".",th:"ใส่วิธีที่คุณชอบให้ตอบลงใน "+M("Settings → Instructions for Claude")},instrSrc:"https://support.claude.com/en/articles/10185728",
 training:{en:"Settings → Privacy → “Help improve our AI models” switch.",th:"Settings → Privacy → สวิตช์ “Help improve our AI models”"},trainingSrc:"https://privacy.claude.com/en/articles/12109829",
 remove:{en:"Settings → Account → Delete account. On Pro or Max, cancel first and wait for the paid month to end.",th:"Settings → Account → Delete account ถ้าใช้ Pro หรือ Max ยกเลิกก่อน รอให้เดือนที่จ่ายแล้วหมด"},removeSrc:"https://support.claude.com/en/articles/9028421",
 privacy:{to:"privacy@anthropic.com",url:"mailto:privacy@anthropic.com"}},
{id:"gemini",name:"Gemini",company:"Google",
 export:{en:"Go to "+M("takeout.google.com")+" → Deselect all → tick “Gemini” (your Gems) and “My Activity” → in My Activity pick only “Gemini Apps” (chats, pictures, uploads).",th:"ไปที่ "+M("takeout.google.com")+" → Deselect all → ติ๊ก “Gemini” (Gems ของคุณ) และ “My Activity” → ใน My Activity เลือกแค่ “Gemini Apps” (แชท รูป ไฟล์ที่อัปโหลด)"},exportSrc:"https://support.google.com/gemini/answer/16920332",
 arrives:{en:"A link by email, usually the same day.",th:"ลิงก์ส่งมาทางอีเมล ส่วนใหญ่ได้ภายในวันเดียว"},
 memory:{en:"Saved memories: "+M("Settings & help → Personal context")+" (gemini.google.com/saved-info).",th:"ความจำ: "+M("Settings & help → Personal context")+" (gemini.google.com/saved-info)"},memorySrc:"https://support.google.com/gemini/answer/16413516",
 import:{en:M("Settings & help → Import memory to Gemini")+". Paste the moving letter as memory. “Import chats” takes a ChatGPT or Claude export .zip (up to 5 GB, 5 a day) and brings the old chats in. Personal accounts, 18+. Not in the EU, Switzerland or UK. Google may use imported chats to train its models.",th:M("Settings & help → Import memory to Gemini")+" วางจดหมายย้ายบ้านเป็นความจำ ปุ่ม “Import chats” รับไฟล์ .zip จาก ChatGPT หรือ Claude (ไม่เกิน 5 GB วันละ 5 ไฟล์) เอาแชทเก่าเข้ามาได้เลย บัญชีส่วนตัว อายุ 18 ขึ้นไป ใช้ในยุโรป สวิตเซอร์แลนด์ และอังกฤษไม่ได้ Google อาจเอาแชทที่นำเข้าไปฝึก AI"},importSrc:"https://support.google.com/gemini/answer/16868299",
 instr:{en:"Anything left over goes into "+M("Personal context")+".",th:"ที่เหลือใส่ใน "+M("Personal context")},
 training:{en:"Settings & help → Activity → turn off “Keep Activity”. Google still holds chats up to 72 hours.",th:"Settings & help → Activity → ปิด “Keep Activity” Google ยังเก็บแชทไว้ไม่เกิน 72 ชั่วโมง"},trainingSrc:"https://support.google.com/gemini/answer/13594961",
 remove:{en:"Chats: Activity → Delete. The whole Google account is a separate step, and takes Gmail and Photos with it.",th:"ลบแชท: Activity → Delete ลบบัญชี Google ทั้งหมดเป็นอีกเรื่อง Gmail และรูปจะหายไปด้วย"},removeSrc:"https://support.google.com/accounts/answer/32046",
 privacy:{to:"Google Data Protection Office form",url:"https://support.google.com/policies/contact/data_privacy_office"}},
{id:"copilot",name:"Copilot",company:"Microsoft",
 export:{en:"Microsoft privacy dashboard ("+M("account.microsoft.com/privacy")+") → Copilot → Copilot app activity history → “Export all activity history”.",th:"หน้าความเป็นส่วนตัวของ Microsoft ("+M("account.microsoft.com/privacy")+") → Copilot → Copilot app activity history → “Export all activity history”"},exportSrc:"https://support.microsoft.com/en-us/privacy/manage-your-copilot-activity-history-in-the-privacy-dashboard",
 arrives:{en:"A CSV spreadsheet file, downloaded straight away.",th:"ไฟล์ตาราง CSV ดาวน์โหลดได้ทันที"},
 memory:{en:"Memories: "+M("Settings → Personalization → Saved memories")+".",th:"ความจำ: "+M("Settings → Personalization → Saved memories")},memorySrc:"https://support.microsoft.com/en-us/privacy/microsoft-copilot/privacy-controls",
 import:{en:"No import button. Paste the moving letter into a new chat and ask it to remember; check Saved memories after.",th:"ไม่มีปุ่มนำเข้า วางจดหมายย้ายบ้านในแชทใหม่ บอกให้จำไว้ แล้วเปิดดู Saved memories"},
 training:{en:"Microsoft says the new Copilot app (from 18 Aug 2026) doesn't use your chats to train its foundation models. Older app: Profile → Privacy → turn off “Training on conversation activity” and “Training on voice conversations”.",th:"Microsoft บอกว่าแอป Copilot ใหม่ (ตั้งแต่ 18 ส.ค. 2026) ไม่เอาแชทไปฝึกโมเดลหลัก แอปเก่า: Profile → Privacy → ปิด “Training on conversation activity” และ “Training on voice conversations”"},trainingSrc:"https://support.microsoft.com/en-us/privacy/microsoft-copilot/activity-history",
 remove:{en:"Copilot uses your Microsoft account; closing it takes Outlook and OneDrive with it.",th:"Copilot ใช้บัญชี Microsoft ปิดบัญชีแล้ว Outlook และ OneDrive หายไปด้วย"},removeSrc:"https://www.microsoft.com/en-us/privacy/privacystatement",
 privacy:{to:"aka.ms/privacyresponse",url:"https://aka.ms/privacyresponse"}},
{id:"meta",name:"Meta AI",company:"Meta",
 export:{en:"Meta AI app → Menu → Settings → Data & privacy → Manage your information → Download your information → Create export. Pick JSON.",th:"แอป Meta AI → Menu → Settings → Data & privacy → Manage your information → Download your information → Create export เลือก JSON"},exportSrc:"https://www.meta.com/help/artificial-intelligence/1314808549771571/",
 arrives:{en:"Email can take up to 30 days; then 4 days to download. Chats you deleted aren't in it.",th:"อีเมลอาจนานถึง 30 วัน แล้วมีเวลาดาวน์โหลด 4 วัน แชทที่ลบไปแล้วไม่อยู่ในไฟล์"},
 memory:{en:"Meta's help pages don't say where memory lives. Ask it: “What do you remember about me?”",th:"หน้าช่วยเหลือของ Meta ไม่ได้บอกว่าความจำอยู่ตรงไหน ถามมันเลย: “คุณจำอะไรเกี่ยวกับฉันได้บ้าง”"},
 import:{en:"No import button. Paste the moving letter into a chat.",th:"ไม่มีปุ่มนำเข้า วางจดหมายย้ายบ้านในแชท"},
 training:{en:"No switch on Meta's help pages. Meta says it uses your AI chats to improve AI at Meta.",th:"หน้าช่วยเหลือของ Meta ไม่มีสวิตช์นี้ Meta บอกว่าใช้แชทกับ AI ไปปรับปรุง AI ของ Meta"},trainingSrc:"https://www.meta.com/help/artificial-intelligence/2457110494637611/",
 remove:{en:"Settings → Data & privacy → Manage your information → “Delete all chats and media”.",th:"Settings → Data & privacy → Manage your information → “Delete all chats and media”"},removeSrc:"https://www.meta.com/help/artificial-intelligence/2457110494637611/",
 privacy:{to:"help.meta.com/support/privacy",url:"https://help.meta.com/support/privacy/"}},
{id:"grok",name:"Grok",company:"xAI",
 export:{en:"Settings → Data Controls → download your data.",th:"Settings → Data Controls → ดาวน์โหลดข้อมูล"},exportSrc:"https://x.ai/legal/faq",
 arrives:{en:"xAI's pages don't give the format or wait.",th:"หน้าของ xAI ไม่ได้บอกรูปแบบไฟล์หรือเวลารอ"},
 memory:{en:"Ask it: “What do you remember about me?”",th:"ถามมันเลย: “คุณจำอะไรเกี่ยวกับฉันได้บ้าง”"},
 import:{en:"No import button. Paste the moving letter into a chat.",th:"ไม่มีปุ่มนำเข้า วางจดหมายย้ายบ้านในแชท"},
 training:{en:"Settings → Data Controls → untick “Improve the model”. Private Chat isn't used for training, xAI says.",th:"Settings → Data Controls → เอาติ๊ก “Improve the model” ออก xAI บอกว่า Private Chat ไม่ถูกเอาไปฝึก"},trainingSrc:"https://x.ai/legal/faq",
 remove:{en:"Settings → Data Controls → Delete Account (or Delete All Conversations). Deleted within 30 days.",th:"Settings → Data Controls → Delete Account (หรือ Delete All Conversations) ลบภายใน 30 วัน"},removeSrc:"https://x.ai/legal/faq",
 privacy:{to:"x.ai/privacy-portal",url:"https://x.ai/privacy-portal/"}},
{id:"perplexity",name:"Perplexity",company:"Perplexity",
 export:{en:"Go to "+M("perplexity.ai/account/details")+" → “Export my data”.",th:"ไปที่ "+M("perplexity.ai/account/details")+" → “Export my data”"},exportSrc:"https://www.perplexity.ai/help-center/en/articles/11564568",
 arrives:{en:"A link by email.",th:"ลิงก์ส่งมาทางอีเมล"},
 memory:{en:"Ask it: “What do you remember about me?”",th:"ถามมันเลย: “คุณจำอะไรเกี่ยวกับฉันได้บ้าง”"},
 import:{en:"No import button. Paste the moving letter into a chat.",th:"ไม่มีปุ่มนำเข้า วางจดหมายย้ายบ้านในแชท"},
 training:{en:"Account settings → Preferences → turn off “AI data retention”. Counts from that day on.",th:"Account settings → Preferences → ปิด “AI data retention” มีผลตั้งแต่วันที่ปิด"},trainingSrc:"https://www.perplexity.ai/help-center/en/articles/11564572",
 remove:{en:"Account settings → Delete account. Takes up to 30 days; signing back in cancels it.",th:"Account settings → Delete account ใช้เวลาถึง 30 วัน ถ้าล็อกอินกลับจะยกเลิกการลบ"},removeSrc:"https://www.perplexity.ai/help-center/en/articles/11564562",
 privacy:{to:"perplexity.typeform.com/datarequest",url:"https://perplexity.typeform.com/datarequest"}},
{id:"deepseek",name:"DeepSeek",company:"DeepSeek",
 export:{en:"DeepSeek's privacy policy says you can copy or delete chat history in Settings. Guides show "+M("Settings → Data → Export data")+".",th:"นโยบายความเป็นส่วนตัวของ DeepSeek บอกว่าคัดลอกหรือลบประวัติแชทได้ใน Settings คู่มือทั่วไปบอกว่าอยู่ที่ "+M("Settings → Data → Export data")},exportSrc:"https://cdn.deepseek.com/policies/en-US/deepseek-privacy-policy.html",
 arrives:{en:"A JSON file, by those guides. DeepSeek stores data in China.",th:"ไฟล์ JSON ตามคู่มือ DeepSeek เก็บข้อมูลไว้ในจีน"},
 memory:{en:"Ask it: “What do you remember about me?”",th:"ถามมันเลย: “คุณจำอะไรเกี่ยวกับฉันได้บ้าง”"},
 import:{en:"No import button. Paste the moving letter at the start of each new chat.",th:"ไม่มีปุ่มนำเข้า วางจดหมายย้ายบ้านตอนเริ่มแชทใหม่ทุกครั้ง"},
 training:{en:"The privacy policy gives you the right to opt out of training. Guides show a switch, “Improve the model for everyone”, in Settings.",th:"นโยบายให้สิทธิ์ขอไม่ให้เอาไปฝึก คู่มือบอกว่ามีสวิตช์ “Improve the model for everyone” ใน Settings"},trainingSrc:"https://cdn.deepseek.com/policies/en-US/deepseek-privacy-policy.html",
 remove:{en:"Delete chats in Settings; for the account, write to privacy@deepseek.com if you can't find the button.",th:"ลบแชทใน Settings ถ้าหาปุ่มลบบัญชีไม่เจอ เขียนถึง privacy@deepseek.com"},
 privacy:{to:"privacy@deepseek.com",url:"mailto:privacy@deepseek.com"}},
{id:"mistral",name:"Le Chat / Vibe",company:"Mistral AI",
 export:{en:"Mistral's export tool → Export. (Mistral's help pages now call Le Chat “Vibe”.)",th:"เครื่องมือ export ของ Mistral → Export (หน้าช่วยเหลือของ Mistral เรียก Le Chat ว่า “Vibe” แล้ว)"},exportSrc:"https://help.mistral.ai/en/articles/347623",
 arrives:{en:"Mistral's pages don't give the format.",th:"หน้าของ Mistral ไม่ได้บอกรูปแบบไฟล์"},
 memory:{en:"Memories (beta) in Settings: view, add, edit, delete.",th:"Memories (ทดลอง) ใน Settings ดู เพิ่ม แก้ ลบได้"},memorySrc:"https://help.mistral.ai/en/articles/396497",
 import:{en:"No import button. Paste the moving letter into a chat, then add the parts you want to Memories.",th:"ไม่มีปุ่มนำเข้า วางจดหมายย้ายบ้านในแชท แล้วเพิ่มส่วนที่อยากให้จำลงใน Memories"},importSrc:"https://help.mistral.ai/en/articles/396497",
 training:{en:"Personal accounts start switched on. Web: Admin panel → Vibe → Privacy → turn off “Allow your interactions to be used to train our models”. Phone: Settings → Data & Account Controls → untick “Enable data sharing”.",th:"บัญชีส่วนตัวเปิดไว้ตั้งแต่แรก เว็บ: Admin panel → Vibe → Privacy → ปิด “Allow your interactions to be used to train our models” มือถือ: Settings → Data & Account Controls → เอาติ๊ก “Enable data sharing” ออก"},trainingSrc:"https://help.mistral.ai/en/articles/455207",
 remove:{en:"Admin panel → Account → Danger Zone → Delete account.",th:"Admin panel → Account → Danger Zone → Delete account"},removeSrc:"https://help.mistral.ai/en/articles/347619",
 privacy:{to:"Mistral privacy request form",url:"https://help.mistral.ai/en/articles/347639"}},
{id:"kimi",name:"Kimi",company:"Moonshot AI",
 export:{en:"No bulk export on Kimi's pages. Copy the chats you need one by one with the Copy button, or send the request letter below.",th:"หน้าของ Kimi ไม่มีปุ่ม export ทั้งหมด คัดลอกแชทที่ต้องการทีละอันด้วยปุ่ม Copy หรือส่งจดหมายขอข้อมูลข้างล่าง"},exportSrc:"https://www.kimi.com/user/agreement/userPrivacy?version=v2",
 arrives:{en:"Kimi stores data in China.",th:"Kimi เก็บข้อมูลไว้ในจีน"},
 memory:{en:"Memory is in Kimi's settings: view, manage or turn off.",th:"ความจำอยู่ในการตั้งค่าของ Kimi ดู จัดการ หรือปิดได้"},
 import:{en:"No import button. Paste the moving letter into a chat.",th:"ไม่มีปุ่มนำเข้า วางจดหมายย้ายบ้านในแชท"},
 training:{en:"By email only: write to support@moonshot.cn. Done in 5–7 working days, past and future chats.",th:"ทางอีเมลเท่านั้น: เขียนถึง support@moonshot.cn ใช้เวลา 5–7 วันทำการ มีผลทั้งแชทเก่าและใหม่"},trainingSrc:"https://www.kimi.com/help/others/data-usage",
 remove:{en:"App: Settings → Account Security → Delete Account. Web: Settings → Account Settings → Delete Account.",th:"แอป: Settings → Account Security → Delete Account เว็บ: Settings → Account Settings → Delete Account"},removeSrc:"https://www.kimi.com/help/others/account-deletion",
 privacy:{to:"support@moonshot.cn",url:"mailto:support@moonshot.cn"}},
{id:"own",name:{en:"My own computer",th:"คอมพิวเตอร์ของฉัน"},
 export:{en:"Chats sit in the app's folder on your computer. Copy that folder.",th:"แชทอยู่ในโฟลเดอร์ของแอปในเครื่องคุณ คัดลอกโฟลเดอร์นั้นไป"},
 arrives:{en:"Take the folder on a USB stick or cloud drive.",th:"ใส่ USB หรือไดรฟ์ออนไลน์ไป"},
 memory:{en:"Standing instructions live in the app's “system prompt” box. Copy them.",th:"คำสั่งประจำอยู่ในช่อง “system prompt” ของแอป คัดลอกไป"},
 import:{en:"Paste the moving letter into the app's “system prompt” box (the instructions it reads before every chat). See the apps below.",th:"วางจดหมายย้ายบ้านในช่อง “system prompt” ของแอป (คำสั่งที่มันอ่านก่อนทุกแชท) ดูรายชื่อแอปข้างล่าง"},
 remove:{en:"Delete the folder when you're ready.",th:"พร้อมเมื่อไหร่ ลบโฟลเดอร์ทิ้ง"}}
];
